### ISSUE TITLE
Go driver / programmatic access

### ISSUE THREAD

**Issue by jkodumal** [liquidata-inc/dolt#107]
Is there a plan for a Go driver, or some other way to query a Dolt database programmatically? Or is programmatic querying not a reasonable use case for Dolt?

**Comment by oscarbatori** [comment]
@jkodumal thanks for your interest in Dolt. We are currently heavily focused on automated interfaces. Python and Go are in the near future (like, very near), and we have devoted a decent quantity of resources to SQL. 

Let me know if you'd like to discuss your use-case further.

**Comment by timsehn** [comment]
Specifically, if you run dolt sql-server, you will get a MySQL compatible server running on your box.

```timothys-mbp:usda-all-foods timsehn$ dolt sql-server --help
NAME
	dolt sql-server - Start a MySQL-compatible server.

SYNOPSIS
	dolt sql-server [-H <host>] [-P <port>] [-u <user>] [-p <password>] [-t <timeout>] [-l <loglevel>] [-r]

DESCRIPTION
	Start a MySQL-compatible server which can be connected to by MySQL
	clients.
	
	Currently, only SELECT statements are operational, as support for
	other statements is
	still being developed.
	

OPTIONS
	-H <Host address>, --host=<Host address>
	  Defines the host address that the server will run on (default
	  `localhost`)
	
	-P <Port>, --port=<Port>
	  Defines the port that the server will run on (default `3306`)
	
	-u <User>, --user=<User>
	  Defines the server user (default `root`)
	
	-p <Password>, --password=<Password>
	  Defines the server password (default ``)
	
	-t <Connection timeout>, --timeout=<Connection timeout>
	  Defines the timeout, in seconds, used for connections
	  A value of `0` represents an infinite timeout (default `30`)
	
	-r, --readonly
	  Disables modification of the database
	
	-l <Log level>, --loglevel=<Log level>
	  Defines the level of logging provided
	  Options are: `debug`, `info`, `warning`, `error`, `fatal` (default
	  `info`)
```

To execute any Dolt commands (ie. commit, push, pull), you'll have to use the command line but you'll be able to run SQL to read/modify the database. Not all SQL write functionality is supported just yet but we're working on it. Our newest release coming out this week will have UPDATE and INSERT support. 

Eventually, we want to expose dolt functionality like commit through the SQL interface but that will require some design.
