### ISSUE TITLE
Should "" columns in CSVs be cast to NULL for numeric types on import?

### ISSUE THREAD

**Issue by timsehn** [liquidata-inc/dolt#115]
Common CSVs distributed on the internet make blank numeric columns ,"", instead of ,,. This requires some CSV parsing to fix which is annoying. Maybe we should auto cast those to NULL for numeric types or add it as an option on import.

**Comment by oscarbatori** [comment]
@timsehn did we ever resolve this or make a decision?

**Comment by timsehn** [comment]
@katie implemented the functionality ```,"",``` is a string ```,,``` is a NULL. This can be closed.
