### ISSUE TITLE
Dolt should allow null values in primary key columns

### ISSUE THREAD

**Issue by zachmu** [liquidata-inc/dolt#139]
Assuming this is a product decision rather than a technical one. Brian?

**Comment by reltuk** [comment]
@zachmu Where do you see this in SQL?

From MySQL Reference Manual:

> PRIMARY KEY
> 
> A unique index where all key columns must be defined as NOT NULL.

https://dev.mysql.com/doc/refman/8.0/en/create-table.html


From PostgreSQL Manual:

> Adding a primary key will automatically create a unique B-tree index on the column or group of columns listed in the primary key, and will force the column(s) to be marked NOT NULL.

https://www.postgresql.org/docs/11/ddl-constraints.html

**Comment by reltuk** [comment]
SQL appears to allow this as an accident of history:

> Each row in a table with a primary key must have a unique combination of values in its primary key columns. For the purposes of determining the uniqueness of primary key values, NULL values are considered distinct from all other values, including other NULLs. If an INSERT or UPDATE statement attempts to modify the table content so that two or more rows have identical primary key values, that is a constraint violation.
> 
> According to the SQL standard, PRIMARY KEY should always imply NOT NULL. Unfortunately, due to a bug in some early versions, this is not the case in SQLite. Unless the column is an INTEGER PRIMARY KEY or the table is a WITHOUT ROWID table or the column is declared NOT NULL, SQLite allows NULL values in a PRIMARY KEY column. SQLite could be fixed to conform to the standard, but doing so might break legacy applications. Hence, it has been decided to merely document the fact that SQLite allowing NULLs in most PRIMARY KEY columns.

https://www.sqlite.org/lang_createtable.html

**Comment by reltuk** [comment]
(In SQL semantics, `NULL`s do not compare equal to other `NULL`s, and so having a unique constraint where a field is nullable is weird...)

**Comment by oscarbatori** [comment]
I am closing this as it seems that it's not the norm, and we discussed offline and reached the same conclusion.
