### ISSUE TITLE
ALTER TABLE ... ADD ... without parentheses does not parse.

### ISSUE THREAD

**Issue by reltuk** [liquidata-inc/dolt#149]
```
doltsql> alter table labels add column SomeColumn varchar(100);
Error parsing SQL: syntax error at position 41 near 'SomeColumn'.
```

The above should parse. Currently it requires `alter table labels add column (SomeColumn varchar(100))` instead.

See: https://dev.mysql.com/doc/refman/8.0/en/alter-table.html

**Comment by timsehn** [comment]
This is fixed.
