### ISSUE TITLE
What are the limitations of doit in terms of dataset size?

### ISSUE THREAD

**Issue by xiaodaigh** [liquidata-inc/dolt#17]
Can it handle gigabyte size data?

**Comment by timsehn** [comment]
We have a 17Gb dataset in there. It can handle it. Diffs and merges are very fast at that scale. Some SQL (like joins) will be slow. For those SQL use cases we recommend an export and and import into your favorite RDBMS like MySQL or PostGreSQL.

**Comment by timsehn** [comment]
Theoretically, it should scale to the size of the disk available. We don't have a way to distribute the repo across multiple disks yet but we have ideas about how we would do that. Imports and exports get pretty slow for big databases though.
