### ISSUE TITLE
Make Dolt available on Homebrew

### ISSUE THREAD

**Issue by bitigchi** [liquidata-inc/dolt#180]
Hello,

I would be really convenient for us macOS users to be able to install dolt via Homebrew. It is easy to set up, and users can install dolt just via a simple command like `brew install dolt`.

For more information: https://brew.sh

**Comment by oscarbatori** [comment]
@bitigchi thanks for your interest in Dolt. We are going to do that in the very near future. I will update this issue when we have created a formula.

**Comment by bitigchi** [comment]
Thank you!

**Comment by ankane** [comment]
Dolt is now on Homebrew: https://github.com/Homebrew/homebrew-core/pull/52821

**Comment by timsehn** [comment]
Thanks! When we do a release do we juts update the version and the SHA in that file and make a PR against homebrew-core?

**Comment by ankane** [comment]
Yeah, exactly. Update the `url` and `sha256` and submit a PR. Here's an example: https://github.com/Homebrew/homebrew-core/commit/990e791c361fa045e9dedfde830709c7d129f257

**Comment by timsehn** [comment]
Cool. We're going to script it up as part of the release process. Thanks
for the contribution!
