### ISSUE TITLE
Cannot add columns

### ISSUE THREAD

**Issue by bitigchi** [liquidata-inc/dolt#181]
I am trying out Dolt, and have a basic [repository](https://www.dolthub.com/repositories/bitigchi/old-turkic-vocabulary/data/new_column/vocabulary). I want to add a column named "word_class", but was not successful so far. What I have tried is:

1. use `dolt sql --query 'ALTER TABLE vocabulary ADD word_class VARCHAR (20) NOT NULL'`
2. use the dolt sql command line with the same command
3. use `schema add-column --not-null --tag=3 vocabulary word_class VARCHAR (20) NOT NULL`

For the third one, I am getting an error saying `varchar is not a valid type for this new column`
For the first two `Error parsing SQL: syntax error at position 37 near 'word_class` is the error I am getting.

I am relatively new to databases, and _maybe_ I _am_ doing something wrong, so if someone could guide me, that would be great. Please close the issue if it's not a bug.

**Comment by zachmu** [comment]
Hi bitigchi,

Thanks for the report!

Your example 1) is valid SQL and should work. This is a bug with the SQL parser library we're using, which we plan to fix but haven't yet. You need to put the column definition in parenthesis like this:

dolt sql --query 'ALTER TABLE vocabulary ADD (word_class VARCHAR (20) NOT NULL)'

We'll leave this open until we've fixed the parser.

**Comment by bitigchi** [comment]
Thank you!

**Comment by timsehn** [comment]
The parser supports this statemht now :-)
