### ISSUE TITLE
Wide tables create poor query performance

### ISSUE THREAD

**Issue by andrew-wm-arthur** [liquidata-inc/dolt#194]
On the [MNIST handwritten digits data set](https://www.dolthub.com/repositories/andy/MNIST-handwritten-digits) (787 columns) query performance is very poor. On the order of several minutes for a 70K row data set.

`time dolt sql -q 'SELECT count(id) FROM samples'`
`real	12m22.745s
user	12m25.863s
sys	0m1.296s`

**Comment by reltuk** [comment]
Thanks for the great report. Resolved here: https://github.com/liquidata-inc/dolt/commit/9611b2d2ca9187706f83cff2c7313ff038a71566.
