### ISSUE TITLE
Questions regarding Dolt for dbdb.io

### ISSUE THREAD

**Issue by vidhartbhatia** [liquidata-inc/dolt#238]
These questions are mainly about the structure and implementation of Dolt for an Entry in [dbdb.io](https://dbdb.io/db/dolt).

1. Storage Model: What kind of storage models does Dolt support (e.g., NSM, DSM).
2. Storage Architecture: Is the system a disk-oriented or in-memory DBMS? 
3. Storage Organization: How is Dolt's underlying storage manager implemented?
4. Checkpoints: How does Dolt take checkpoints?
5. Compression: Does Dolt support database compression? What algorithms do they use? Do they have to decompress data first before processing it during query execution?
6. Logging: How does the system support data durability? What kind of logging scheme does it use (e.g., physical, logical, physiological)?
7. Query Execution: What query processing model does Dolt support (e.g., iterator vs. vectorized)? What kind of intra-query parallelism does it support?
8. Joins: What join algorithms does Dolt support? What is notable or special about them (e.g., low-memory, parallelism)?
9. Concurrency Control: Does Dolt support transactions and if so what concurrency control scheme does it use?
10. Data Model: What data model does Dolt support? 
11. Indexes: What index data structures does Dolt support? What is the default?

I appreciate your help with this!

**Comment by timsehn** [comment]
We are already in dbdb.io. https://dbdb.io/db/dolt

**Comment by vidhartbhatia** [comment]
Yes sorry I should have specified, I spoke with Oscar regarding this. For the dbdb entry, we require public citations to verify the facts mentioned in the articles. I wrote it based on what Oscar sent me, so we were hoping that we could use this issue as a citation to confirm what we wrote is correct and have the information from the developers here for the record.

**Comment by timsehn** [comment]
Great. I think we can probably give you links to the code that implements all this stuff. @oscarbatori will help with that.

**Comment by oscarbatori** [comment]
### Storage Model: 
What kind of storage models does Dolt support (e.g., NSM, DSM)?
> The table storage is NSM with clustered primary keys. Block boundaries for internal and leaf nodes are chosen by a rolling hash of the block contents, and then entire dataset is content-addressed as a Merkle Tree of these component blocks.

### Storage Architecture: 
Is the system a disk-oriented or in-memory DBMS?
> The storage is disk oriented. We will support fanning out to multiple machines for large datasets in the medium term. For now we can support ~100 GB datasets.

### Storage Organization: 
How is Dolt's underlying storage manager implemented?
> Above-mentioned content-addressed blocks are stored in write-once table files with a static binary-searchable index on the end. A compaction phase rolls up table files when their number grows past a certain threshold.

### Checkpoints: 
How does Dolt take checkpoints?
> Dolt doesn't explicitly take checkpoints because it doesn't have mutable database files. A manifest stores a pointer to all currently active table files, and it is updated atomically on every mutation of the database.

### Compression: 
Does Dolt support database compression? 
> Yes.

What algorithms do they use? 
> All chunks are compressed with snappy in storage, and are decompressed as they are read into the block cache.

Do they have to decompress data first before processing it during query execution?
> It is necessary to decompress to process queries.

### Logging

How does the system support data durability? 
> New data is only written once, to new table files containing the new chunks. Those table files are flushed to disk before the manifest referencing them is updated.

What kind of logging scheme does it use (e.g., physical, logical, physiological)?
> There is no logging support.

### Query Execution: 

What query processing model does Dolt support (e.g., iterator vs. vectorized)? 
> Iterator based query processing.

What kind of intra-query parallelism does it support?
> No intra-query parallelism.

### Joins:
What join algorithms does Dolt support? 
> Naive algorithm, not yet performant, though we intend to improve it in the very near future (weeks to months).

What is notable or special about them (e.g., low-memory, parallelism)?
> Not applicable.

### Concurrency Control: 
Does Dolt support transactions and if so what concurrency control scheme does it use?
> Transactions are not implemented. Concurrent SQL sessions on the same dolt checkout will see something like read committed, with an auto-commit on each executed SQL statement.

### Data Model: 

What data model does Dolt support?
> Relational. We will have JSON and raw byte datatypes, which I argue makes relational cover the others, with the proviso that we lose the optimizations gained from supporting only a single model.

### Indexes: 
What index data structures does Dolt support? What is the default?
> Dolt currently only supports a B-tree like index structure, and currently only for table primary keys.
