### ISSUE TITLE
Weird error message when using dolt import

### ISSUE THREAD

**Issue by oscarbatori** [liquidata-inc/dolt#275]
```
[oscarbatori:scratch] >> dolt table import people --pk=first -c test_data.csv
Data already exists.  Use -f to overwrite.
```
Should say "Table already exists".

**Comment by timsehn** [comment]
I think the export table path was changed by the PR above not the import path.

**Comment by timsehn** [comment]
@andrew-wm-arthur is gonna fix and make a bats test.

**Comment by timsehn** [comment]
So it turns out that error code was used on both the import and export path. So, when we merged the PR one of our integration tests failed. @andrew-wm-arthur is going to make two different paths, one for export and one for import.
