### ISSUE TITLE
dolt init seems to not recognize arguments

### ISSUE THREAD

**Issue by oscarbatori** [liquidata-inc/dolt#277]
From the command line:
```
$ dolt init --help
NAME
        dolt init - Create an empty Dolt data repository

SYNOPSIS
        dolt init [<options>] [<path>]
```
But when I run something like:
```
$ dolt init foo/bar
```
a repo is created in `pwd` rather than `foo/bar`.

**Comment by u5surf** [comment]
Its long description said `This command creates an empty Dolt data repository in the current directory.`
https://github.com/liquidata-inc/dolt/blob/071b9da5e137fea544466050c3d16a331b1a7575/go/cmd/dolt/commands/init.go#L37
So that It can only specify the current directory. It should remove the `<path>` in this SYNOPSIS.

**Comment by oscarbatori** [comment]
Good point, but I think the thrust is that we want Dolt to create in the
specified repo, as switching around when you want to create a few is
annoying.

**Comment by 7vikpeculiar** [comment]
Hi
Can I work on this issue  ?

**Comment by timsehn** [comment]
You sure can :-)

**Comment by timsehn** [comment]
I would just remove path from the command spec.

**Comment by 7vikpeculiar** [comment]
Hi, 
In the master branch, there are no options anymore, also checked it using the command line

https://github.com/liquidata-inc/dolt/blob/master/go/cmd/dolt/commands/init.go

![image](https://user-images.githubusercontent.com/23234353/87121812-487e9580-c2a1-11ea-8f05-e49df25dddfe.png)

Is there a different branch I am supposed to look at ? (I don't get which branch to switch to see the file linked above https://github.com/liquidata-inc/dolt/issues/277#issuecomment-570053007)

**Comment by timsehn** [comment]
It's fixed! You are magic. Sorry we didn't close the bug.
