### ISSUE TITLE
Doing CDC with Dolt

### ISSUE THREAD

**Issue by joeblew99** [liquidata-inc/dolt#28]
Exploring uses cases with Dolt.

Maybe the hub already does a change to the data is just like CDC, and git Servers tell you when someone makea commit. But with a CDC you want to be able to query and get an event when the data that is part of the Query Result Set changes.

PS. Polling is cheating !

**Comment by oscarbatori** [comment]
@joeblew99 to clarify, is this a feature request? 

I see two types of CDC use-case for Dolt:
1. a downstream Dolt or other kind of process is capturing changes to a Dolt repo, and thus wants to be notified in the way you are seem to be implying
2. Dolt a repository is capturing changes to the data returned by some endpoint, say an API, and we want to record a meaningful commit in the Dolt repo only when the data changes

We currently support (2), and will have documented examples of how to instrument such a workflow in Python, but Dolt upstreams do not notify down-streams when they have changes.

Let us know if you have thoughts on this, we are excited to discuss Dolt, and the value it can create.

-Oscar

**Comment by joeblew99** [comment]
thinking about CDC.. Is the HUB code in this repo ?

**Comment by oscarbatori** [comment]
The hub code is not open source, and we don't have any immediate plans to change that.

By DC, do you mean capturing changes in some upstream data source? Can you give me an example? I have been working on some "cookbooks" for this sort of thing, so eager to hear what you have come across.

**Comment by joeblew99** [comment]
Sorry yes i mean CDC ( change data capture).

Use case. You have a data type and you want to do subscriptions so you can
tell all subscribers when the data changes ( typical a CUD = Create,
Update, delete).

**Comment by oscarbatori** [comment]
For Dolt the use-case you are describing implies that Dolt repositories are "live" processes running at some known address. In particular the repository being monitored would have to know its list of subscribers to achieve the "push" workflow you are alluding to, where changes are automatically percolated to dependent repos. I don't think this is feasible, or even desirable for Dolt.

For DoltHub it's certainly possible that the application could look at Dolt repos that are configured with an upstream that is itself a DoltHub repo, and then wake them up, and trigger a `dolt pull origin <branch>` update when a commit is posted to `<branch>`. We do not currently support this, but we can see the utility, and we plan something of the sort.

Does this answer your question?
