### ISSUE TITLE
Install Process Failing

### ISSUE THREAD

**Issue by itdependsnetworks** [liquidata-inc/dolt#340]
As per release notes of 0.13, this should be possible `curl -L https://github.com/liquidata-inc/dolt/releases/latest/download/install.sh | bash`, however I am getting an error running that or hardcoding for 13.0 or 13.1.

12.0 is working fine.

**Comment by timsehn** [comment]
We're on this.

**Comment by timsehn** [comment]
Looks like our release process failed to publish the new scripts. Pretty easy fix. Coming soon.

**Comment by reltuk** [comment]
Thank you for the report. The `install.sh` scripts didn't get uploaded with the 0.13.0 and 0.13.1 releases. I've just uploaded and tested them now.

**Comment by timsehn** [comment]
Ken, I'll close this out when you confirm it works for you.

**Comment by itdependsnetworks** [comment]
Looks good, thanks!
