### ISSUE TITLE
Dolt Add Short Option

### ISSUE THREAD

**Issue by itdependsnetworks** [liquidata-inc/dolt#345]
In keeping in line with git, does it not make sense to have it with the git-like options? e.g. it is `git add -A` but in dolt it is `git add -a`. 

Not a big deal, but my muscle memory is hard to break.

**Comment by timsehn** [comment]
We'll fix. Thanks for the bug.

**Comment by timsehn** [comment]
This will go out in the next release. Tip of master has the change.
