### ISSUE TITLE
Running piped SQL file that drops and adds a table produces different results on subsequent runs

### ISSUE THREAD

**Issue by timsehn** [liquidata-inc/dolt#467]
Repo: corona-virus
Branch: case_details_virological_dot_org

This SQL: https://drive.google.com/open?id=1nZJyvSfZspMnIixZtmW3uRM0xYT7dloW

When run twice on the same working set produces no diff and the this diff summary:
```
Timothys-MacBook-Pro:corona-virus timsehn$ dolt diff --summary
diff --dolt a/case_details b/case_details
--- a/case_details @ ugcofv63pv8mqvq40h0esr4p7qm010qo
+++ b/case_details @ p11dee7ecl08h9g8ml3jrpnnqj48o5mm
48,601 Rows Unmodified (98.42%)                                         
0 Rows Added (0.00%)
779 Rows Deleted (1.58%)
0 Rows Modified (0.00%)
0 Cells Modified (0.00%)
(49,380 Entries vs 48,601 Entries)
```
It seems to deterministically delete all rows for the Hubei sheet source key with ID above 20463.

**Comment by zachmu** [comment]
Reproduced this with latest build. Not sure what's happening yet, but have some ideas.
