### ISSUE TITLE
Unable to select log10() of a column from a view

### ISSUE THREAD

**Issue by zachmu** [liquidata-inc/dolt#489]
Dolthub queries to reproduce.

This one works:

https://www.dolthub.com/repositories/Liquidata/corona-virus/query/master?q=select%20*%20from%20time_series%20where%20country_region%20%3D%20%22Italy%22

This one doesn't:

https://www.dolthub.com/repositories/Liquidata/corona-virus/query/master?q=select%20*%2C%20log10%28confirmed_count%29%20from%20time_series%20where%20country_region%20%3D%20%22Italy%22

Other column functions, like concat, work fine:

https://www.dolthub.com/repositories/Liquidata/corona-virus/query/master?q=select%20*%2C%20concat(country_region%2C%20%22%20abc%22)%20from%20time_series%20where%20country_region%20%3D%20%22Italy%22

**Comment by reltuk** [comment]
It's throwing an error because the data set has a value that's not in the range of the `log10` function:

```
doltsql> select log10(1) from dual;
+----------+
| log10(1) |
+----------+
| 0        |
+----------+
doltsql> select log10(0) from dual;
+----------+
| log10(0) |
+----------+
+----------+
error processing results: invalid argument value for logarithm: 0
```
