### ISSUE TITLE
Arbitrary message from doltremoteapi/Dolt in Dolt client

### ISSUE THREAD

**Issue by oscarbatori** [liquidata-inc/dolt#498]
The super schema and unique tags changes necessitate rewriting history of repos, and thus breaking local copy of various repositories. We need users to do some kind of "force pull" operation, but we don't have a way to tell them they need to do this.

To be future proof, we should allow Dolt client to render arbitrary message from remote so that we can furnish users with information about backwards non-compatible changes in the future.

**Comment by andrew-wm-arthur** [comment]
https://github.com/liquidata-inc/dolt/pull/569
