### ISSUE TITLE
Unsure how to see size of a repository

### ISSUE THREAD

**Issue by aidanhs** [liquidata-inc/dolt#507]
Given that databases can be large, I'd really like to know the size of repositories, either via the dolthub UI or in the cloning interface (preferably both!). However, I hunted for a while and couldn't find any information so I have no idea how long my `Liquidata/image-net` clone will take.

(git gives really good progress info on clone and I regularly find this invaluable - and that's for repositories that 'just' contain source code!)

(as an aside, I was looking for some non-social-media 'contact us' link anywhere on dolthub to ask some questions not quite fitting for github, i.e. a form or an e-mail address, and couldn't find anything. On this journey I also noticed the social media links at the bottom of https://www.liquidata.co/ didn't work)

**Comment by timsehn** [comment]
Agreed. Thanks for the feedback.

You can hit me up at tim@liquidata.co. Our help email is: dolthub-help@liquidata.co.

**Comment by timsehn** [comment]
This is implemented and deployed on DoltHub:

https://www.dolthub.com/discover

Thanks for the feedback!
