### ISSUE TITLE
Document support for SQL syntax

### ISSUE THREAD

**Issue by fire** [liquidata-inc/dolt#510]
What support does dolt have for SQL? I'm imagining a feature by feature listing like cockroachdb does.

https://www.cockroachlabs.com/docs/v19.2/cockroach-sql.html 

https://www.cockroachlabs.com/docs/v20.1/sql-grammar.html

**Comment by timsehn** [comment]
Agreed. This is coming. @zachmu is working on it.

**Comment by fire** [comment]
What is the status of this?

**Comment by oscarbatori** [comment]
@fire we are releasing new docs in a matter of days. I will keep you posted personally.

**Comment by zachmu** [comment]
Hi @fire,

These are now available. Please let us know if this meets your expectations.

https://www.dolthub.com/docs/sql/050_supported_features/
https://www.dolthub.com/docs/sql/060_supported_statements/

Zach

**Comment by fire** [comment]
These docs are great, but they revealed the exact state of the support which is good and disappointing. There's work to do though!

**Comment by zachmu** [comment]
Yes, we have a long way to go. The next major feature is unique constraints, followed by foreign keys. Should land within a month.

**Comment by fire** [comment]
I'll close this issue, but the docs have to be maintained as long as people care about dolt.
