### ISSUE TITLE
Feature: `dolt creds import ...`

### ISSUE THREAD

**Issue by tomdottom** [liquidata-inc/dolt#561]
Currently, as far as I can tell, the only way to set up dolt credentials programatically for automated systems is by creating the appropriate files:

- `~/.dolt/config_global.json`
- `~/.dolt/creds/abcxyz.jwk`

I might be preferable to use the cli to import and setup creds. Say:

**Create from env var**
```
echo "${creds_file}" | dolt creds import --use --user-name="me" --user-email="me@dom.com"
```

**Create from file**
```
cat /path/to/creds_file.jwk | dolt creds import --use --user-name="me" --user-email="me@dom.com"
# or
dolt creds import --use --user-name="me" --user-email="me@dom.com" --creds-file=/path/to/creds_file
```

Alternative env vars could be used to provide temporary config:

**Using env var overrides**
```
DOLT_CONFIG_USER_NAME="Me"
DOLT_CONFIG_USER_EMAIL="me@dom.com"
DOLT_CONFIG_CREDS_PATH="...."
```

Or:
```
DOLT_CONFIG_USER_NAME="Me"
DOLT_CONFIG_USER_EMAIL="me@dom.com"
DOLT_CONFIG_CREDS_JWK="{...}"
```

Lastly, a `dolt creds export ...` command may also be useful.

**Comment by timsehn** [comment]
Creds are @reltuk 's baby. Assigning to him.

**Comment by reltuk** [comment]
I love import/export. Great ask. We'll get on it.

For now, the easiest way to use an external cred is maybe to drop the `*.jwk` file into `~/.dolt/creds` and then run `dolt creds use KEY_ID|PUBLIC_KEY`. KEY_ID is the same as the filename without the `.jwk` extension.

So something like...
```sh
$ cp 0gb511i5f5pi4u6o5ihkcaech9112d5o1rdufqbtqkkru.jwk ~/.dolt/creds
$ dolt creds use 0gb511i5f5pi4u6o5ihkcaech9112d5o1rdufqbtqkkru
```

I was just trying out this workflow, and noticed that

```sh
$ cp 0gb511i5f5pi4u6o5ihkcaech9112d5o1rdufqbtqkkru.jwk ~/.dolt/creds
$ dolt login 0gb511i5f5pi4u6o5ihkcaech9112d5o1rdufqbtqkkru
```

also works and pulls the username and email address from the dolthub profile so that you don't have to populate them with `dolt config --add`, but it doesn't behave exactly as I would want. In particular, it still opens the browser. Going to make some behavior changes there, so that if the credential is supplied on the command line there's an initial check with the server and the browser doesn't open if the credentials are already registered. Also going to add a flag so it can fail explicitly without opening a browser if that initial check fails --- better for automation contexts.

Will leave this issue open and communicate here about progress.

Thanks!

**Comment by reltuk** [comment]
Took a pass at `import` in particular in #570. If you get a chance, please take a look and let us know if documentation and first pass at functionality looks reasonable. In particular:

1) No `--use` yet...just uses the cred if there are none registered yet, and leaves it unused otherwise. `--use` can follow on quickly if this isn't totally sufficient.
2) By default, if the cred does get used, it fetches profile information from doltremoteapi if that information is not already available in dolt config. Can be disabled with `--no-profile`

Combined, this makes a CI use of `dolt` a little nicer...`dolt import known-cred.jwk` in a completely clean `DOLT_ROOT_PATH` (or `HOME` after #564) will get a used cred and accurate `user.name` and `user.email` if that cred already works against dolthub.

Very open to feedback here. Thanks again for the suggestion :).

**Comment by tomdottom** [comment]
> I was just trying out this workflow, and noticed that
>
> ```
> $ cp 0gb511i5f5pi4u6o5ihkcaech9112d5o1rdufqbtqkkru.jwk ~/.dolt/creds
> $ dolt login 0gb511i5f5pi4u6o5ihkcaech9112d5o1rdufqbtqkkru
> ```
>
> also works and pulls the username and email address from the dolthub profile

As `dolt login` forces a browser to open it might not be the most appropriate option for automate systems.

> So something like...
>
> ```
$ cp 0gb511i5f5pi4u6o5ihkcaech9112d5o1rdufqbtqkkru.jwk ~/.dolt/creds
$ dolt creds use 0gb511i5f5pi4u6o5ihkcaech9112d5o1rdufqbtqkkru
> ```
>

So I found (and started using) the following in the bats tests:

```
dolt config --global --add user.creds "${CREDS_HASH}"
```

Is there any difference between this and the `dolt creds use ...` command?

**Comment by tomdottom** [comment]
So to confirm, the complete workflow would be:

```shell
dolt import known-cred.jwk
dolt use known-cred
```

Of if using `--no-profile`

```shell
dolt config --global --add user.email "my@email.dev"
dolt config --global --add user.name "Dolt User"
dolt import known-cred.jwk --no-profile
dolt use known-cred
```

If so that would certainly be simpler :)


> Took a pass at `import` in particular in #570. If you get a chance, please take a look and let us know if documentation and first pass at functionality looks reasonable. In particular:
> 
> 1. No `--use` yet...just uses the cred if there are none registered yet, and leaves it unused otherwise. `--use` can follow on quickly if this isn't totally sufficient.
> 2. By default, if the cred does get used, it fetches profile information from doltremoteapi if that information is not already available in dolt config. Can be disabled with `--no-profile`
> 
> Combined, this makes a CI use of `dolt` a little nicer...`dolt import known-cred.jwk` in a completely clean `DOLT_ROOT_PATH` (or `HOME` after #564) will get a used cred and accurate `user.name` and `user.email` if that cred already works against dolthub.
> 
> Very open to feedback here. Thanks again for the suggestion :).

**Comment by reltuk** [comment]
Thanks for your responses here. Quick pass at answers:

> Reading between the lines is strikes me that you expect each credential to be associated with one, and only one, user? This raises the following questions:

A credential cannot be associated with more than one user server-side. The credential is the entirety of the authn that the dolt client uses to communicate with the server – it has to land uniquely on  a particular user when coming in. Another design would be to have cred+username auth to the server, and just ensure the credential is associated with the provided username – we didn't do that. We actually copied GitHub behavior with SSH keys here – GitHub prevents a particular public SSH key being associated with more than one account, and uniquely identifies the auth'd user cloning based on the incoming key.

> If this is the case why not just encode the user into the credential file?

A credential is not specific to the user, but it is associated with a user server-side at a given moment in time...

> If a credential is agnostic of the user, why bother to communicate with the server? Or at least provide a way to skip this check.

We could definitely provide a way to skip the check. As it is, having the credential but not on your dolthub user yet is probably not as useful as having it associated.

> Can a credential exists in two accounts at the same time? This is not a question if it's good practice or not, just if it's possible?

Nope, attempting to add the same public key to a second account it will fail server-side.

> Can a credential be moved between accounts?

Definitely. Delete in one and add in another will result in further interactions with dolt remotes being auth'd as the second account.

> Is there any difference between this and the `dolt creds use ...` command?

There's no functional difference between `dolt creds use ...` and `dolt creds --add user.creds ${KEY_ID_HASH}`, if `${KEY_ID_HASH}.jwk` actually exists in `~/.dolt/creds`.  `dolt creds use` will fail if the key doesn't exist, and will also allow the public key of the credential – which is the thing the server communicates on the credentials page for example, to be used. The filename isn't actually the public key, although it's based on it...

> So to confirm...

Yeah, both the proposed interactions end up in the state described. To further clarify just a bit...

Assuming a completely empty dolt state (no existing credential in the config, no `user.email` and `user.profile` set):

```sh
dolt creds import known-cred.jwk
```
Will:
1. Copy the *.jwk to the right place in `.dolt/creds`
2. Use the new cred as `user.creds`
3. Reach out to doltremoteapi and populate `user.name` and `user.email` if the request is successful.

From the same starting state:
```sh
dolt creds new
dolt creds import known-cred.jwk
```
Would already have a used credential at the time of import, and would only perform 1.

From the same starting state:
```sh
dolt config --global --add user.email "my@email.dev"
dolt config --global --add user.name "Dolt User"
dolt creds import known-cred.jwk
```
Would already have `user.name` and `user.email` in the dolt config, and would perform only steps 1 and 2.

From the same starting state:
```sh
dolt creds import known-cred.jwk --no-profile
```
would explicitly disable the profile fetch and would perform only steps 1 and 2.

Hope this helps. Thanks again!

**Comment by tomdottom** [comment]
Thanks @reltuk the behaviour outlined :point_up:  seems completely reasonable.  From experience the most typical automated workflow I would use is:

```shell
dolt config --global --add user.email "my@email.dev"
dolt config --global --add user.name "Dolt User"
echo "${KNOWN_CREDS_B64}" | base64 --decode > known-cred.jwk
dolt creds import known-cred.jwk
```

However I do appreciate tools which allow me to read files input from stdin and allow me to do:
 
```shell
dolt config --global --add user.email "my@email.dev"
dolt config --global --add user.name "Dolt User"
echo "${KNOWN_CRED_B64}" | base64 --decode | dolt creds import -
```

Does the `import` command support this per chance?

**Comment by reltuk** [comment]
@tomdottom It does! If no filename is provided, it reads the credential contents from stdin. Example bats test here: https://github.com/liquidata-inc/dolt/blob/master/bats/creds.bats#L103

**Comment by tomdottom** [comment]
Works a treat.  Much less error prone than prior setup shenanigans.

:+1:
