### ISSUE TITLE
One SQL Alias is still converted to lower case

### ISSUE THREAD

**Issue by tomdottom** [liquidata-inc/dolt#587]
@zachmu whilst #541 has mostly fixed forced lower case aliases, there is still one edge case.

Aliases trying to change the case of the of the original table name are ignored:

```sql
SELECT
  date as Date,
FROM `states_daily`
LIMIT 5;
```

```cvs
date
2020-02-28 00:00:00 +0000 UTC
2020-02-29 00:00:00 +0000 UTC
2020-03-01 00:00:00 +0000 UTC
2020-03-01 00:00:00 +0000 UTC
2020-03-02 00:00:00 +0000 UTC
```

**Comment by zachmu** [comment]
Thanks for the heads up! The issue here is that the parser is converting reserved words to lower case. Will take a little more work to fix than the last one.

**Comment by zachmu** [comment]
This is fixed as of today's release. Thanks for the report!

```
select 1 as Date;
+------+
| Date |
+------+
| 1    |
+------+
```
