### ISSUE TITLE
Querying dolt_diff_<table> before <table> is committed wipes out MySQL Server

### ISSUE THREAD

**Issue by oscarbatori** [liquidata-inc/dolt#606]
Executing a select statement against dolt_diff tables before the associated table has been committed to wipes out the MySQL server process. Makes sense since presumably the underlying data format has to be queried, but need to handle it on server side with some version of "table not found" where we inform the user of the semantics for VCS tables.

**Comment by timsehn** [comment]
Skipped bats test? Brian wrote a sql-server test harness.
