### ISSUE TITLE
AWS URL Formats ?

### ISSUE THREAD

**Issue by cfljam** [liquidata-inc/dolt#623]
Despite reading your tests and documentation Im having no success with file or AWS remotes on dolt version 0.16.1
 
- I have  a basic repo copied to AWS at aws://dolt-test.s3.ap-southeast-2.amazonaws.com/dolt_test 

```
dolt clone -remote origin --aws-region ap-southeast-2 --aws-creds-file ~/.aws/credentials aws://dolt-test/dolt_test test1
```
gives 
```
cloning aws://dolt-test/dolt_test
error: failed to get remote db
cause: aws url has an invalid format
```
Using the full  Amazon S3 virtual hosted style URL gives the same error.

**Comment by reltuk** [comment]
Our documentation on AWS remotes definitely needs some cleaning up. AWS remotes actually require an S3 bucket and a DynamoDB table.

The URL format for an AWS remote is:

`aws://[dynamodb_table_name:s3_bucket_name]/key_prefix_to_use_in_s3_bucket`

Table files will end up stored in `s3://s3_bucket_name/key_prefix_to_use_in_s3_bucket/...`


You can see some dolt interactions with AWS remotes in our integration tests here:

https://github.com/liquidata-inc/dolt/blob/master/bats/aws-remotes.bats


The dynamo db table needs a single attribute hash key, of type string, named `db`. Terraform for something to that effect looks like:

```terraform
resource "aws_dynamodb_table" "manifests" {
  name           = "dolt-ci-bats-manifests-us-west-2"
  billing_mode   = "PAY_PER_REQUEST"
  hash_key       = "db"
  attribute {
    name = "db"
    type = "S"
  }
}
```

**Comment by cfljam** [comment]
I think Im not getting the S3 bucket naming correct here..does this need further qualification ? ARN?

```
(base) johns-mbp:dolt_test johnmccallum$ aws s3 ls "s3://dolt-test"
                           PRE dolt_test/
(base) johns-mbp:dolt_test johnmccallum$ aws dynamodb describe-table --table-name dolt-test-kiwi
TABLE   2020-04-26T09:52:15.510000+12:00        0       arn:aws:dynamodb:ap-southeast-2:336866532956:table/dolt-test-kiwi       323b4397-21da-4612-b93f-fa7565b91506    dolt-test-kiwi  0       ACTIVE
ATTRIBUTEDEFINITIONS    db      S
BILLINGMODESUMMARY      PAY_PER_REQUEST 2020-04-26T09:52:15.510000+12:00
KEYSCHEMA       db      HASH
PROVISIONEDTHROUGHPUT   0       0       0
(base) johns-mbp:dolt_test johnmccallum$ dolt remote -v
origin aws://[dolt-test-kiwi:dolt_test]/dolt_test {"aws-creds-file":"/Users/johnmccallum/.aws/credentials","aws-region":"ap-southeast-2"}
(base) johns-mbp:dolt_test johnmccallum$ dolt push --set-upstream origin master

error: push failed
cause: NoSuchBucket: The specified bucket does not exist
       	status code: 404, request id: 9EC6C701BD3BF584, host id: mI7UOO3Hss5KwYm1E28thbbb6Gnns69ZRxBtxyncDMo/uk6JxkgGiSMzPBsoAJRY0oWxA7QujPc=
```

**Comment by reltuk** [comment]
That all looks very much right to be, except that the bucket name in the `aws s3 ls` call was `dolt-test`, and the bucket name in the dolt url was `dolt_test`.

Try with `aws://[dolt-test-kiwi:dolt-test]/dolt_test`?

**Comment by cfljam** [comment]
DOH$#@ Thats working now. I can clone it back down with changes.. :-)  Just need to work out the file:// remote idiom now..

**Comment by cfljam** [comment]
So the S3 remote works nicely but how about File?

Making a clone just initialises and doesnt seem to connect. Is there some hidden config_global setting?
```
base) johns-mbp:~ johnmccallum$ dolt clone file:///Users/johnmccallum/Documents/dolttest/dolt_test
cloning file:///Users/johnmccallum/Documents/dolttest/dolt_test
0 of 0 chunks complete. 0 chunks being downloaded currently.
(base) johns-mbp:~ johnmccallum$ cd dolt_test/
(base) johns-mbp:dolt_test johnmccallum$ dolt status
On branch master
nothing to commit, working tree clean
(base) johns-mbp:dolt_test johnmccallum$ dolt log
commit cb18qjk3tke7l0veoh00lru1jl5gkh0b
Author: cfljam <john.mccallum05@gmail.com>
Date:   Sun Apr 26 11:08:01 +1200 2020

	Initialize data repository
```

**Comment by reltuk** [comment]
Hmm...file URLs are pretty subtle too. They probably need UX work in addition to documentation improvements. There are dolt working directories, which is what the dolt client is expecting to be run in, and those can track things like non-committed pending changes in a working set, etc., and then there is a storage layer within the `.dolt` directory that tracks canonical repo state. The current implementation of `file://` URLs wants to be pointed directly to the table storage. So, if I have a repo checked out into a directory like `/home/username/dolt-repo`, I can clone it with:

```sh
$ dolt clone file:///home/username/dolt-repo/.dolt/noms my-cloned-repo
```

Pushes to that remote from the `my-cloned-repo` directory will reflect in the local branches being updated on `/home/username/dolt-repo`, but they won't effect the `repo_state.json` stuff at all, including working set value, etc.

**Comment by reltuk** [comment]
Created a bug for the fact that `dolt clone file:///...` is just rolling forward when the provided target is clearly not a dolt repo. #624. Thank you for the report!

**Comment by cfljam** [comment]
Ok thanks Ive reproduced that...

```
(base) johns-mbp:dolt_test johnmccallum$ dolt clone file:///Users/johnmccallum/Documents/dolttest/dolt_test/.dolt/noms clonedrepo
cloning file:///Users/johnmccallum/Documents/dolttest/dolt_test/.dolt/noms
43 of 43 chunks complete. 0 chunks being downloaded currently.
(base) johns-mbp:dolt_test johnmccallum$ cd clonedrepo/
(base) johns-mbp:clonedrepo johnmccallum$ dolt ls
Tables in working set:
	 Table1
	 Table2


```

**Comment by cfljam** [comment]
Could you clarify if the Dynamo db is needed per database or per bucket? ie If I have a series of databases in one S3 bucket does it only need a single DynamoDb table?

**Comment by reltuk** [comment]
The DynamoDB table can manage multiple repositories in a single bucket. It's unique key where it manages manifest and locking details for the table storage itself is currently the repository name – so the key prefix in the S3 bucket.

**Comment by cfljam** [comment]
perfect Many thanks!
