### ISSUE TITLE
sql-server is unstable

### ISSUE THREAD

**Issue by GodGavin** [liquidata-inc/dolt#632]
thanks ,dolt is a great job，i love it,
but when i use command sql-server create a sqlserver,the server runnning is  unstable,sometimes gone away,somtimes lost connection,and so on,plesese view this photo below，
![dlotmysqlclientbug](https://user-images.githubusercontent.com/64452311/80444084-59c33180-8943-11ea-9291-734fa3e80322.jpg)

**Comment by cfljam** [comment]
same for me

**Comment by GodGavin** [comment]
> same for me
@cfljam glad to receive your messaage ,bro,i just browsed your repository, you konw a lot .i'm a starter programmer with poor english from China,BUT I'M SO HAAPY TO JOIN THE SEA OF CODINNG,RESPECT!

**Comment by bheni** [comment]
By default the read and write timeouts are set to 30 seconds.  You can alter them using the new yaml configuration.  The documentation is currently being worked on, but here are the details:

```
This is an example yaml configuration file showing all supported items and their default values:


	log_level: info

	behavior:
	  read_only: false
	  autocommit: true

	user:
	  name: root
	  password: ""

	listener:
	  host: localhost
	  port: 3306
	  max_connections: 1
	  read_timeout_millis: 30000
	  write_timeout_millis: 30000

	databases: []


SUPPORTED CONFIG FILE FIELDS:

	log_level - Level of logging provided. Options are: `trace', `debug`, `info`, `warning`, `error`, and `fatal`.

	behavior.read_only - If true database modification is disabled.

	behavior.autocommit - If true write queries will automatically alter the working set.  When working with autocommit enabled it is highly recommended that listener.max_connections be set to 1 as concurrency
	issues will arise otherwise.

	user.name - The username that connections should use for authentication.

	user.password - The password that connections should use for authentication.
	listener.host - The host address that the server will run on.  This may be `localhost` or an IPv4 or IPv6 address.

	listener.port - The port that the server should listen on.

	listener.max_connections - The number of simultaneous connections that the server will accept.

	listener.read_timeout_millis - The number of milliseconds that the server will wait for a read operation.

	listener.write_timeout_millis - The number of milliseconds that the server will wait for a write operation.

	databases - a list of dolt data repositories to make available as SQL databases. If databases is missing or empty then the working directory must be a valid dolt data repository which will be made available
	as a SQL database

	databases[i].path - A path to a dolt data repository.

	databases[i].name - The name that the database corresponding to the given path should be referenced via SQL.
``` 

Try changing the timeouts to 10 minutes or something large: (600000)

**Comment by bheni** [comment]
yaml configuration file support was released yesterday in 0.16.2 btw.

**Comment by GodGavin** [comment]
> By default the read and write timeouts are set to 30 seconds. You can alter them using the new yaml configuration. The documentation is currently being worked on, but here are the details:
> 
> ```
> This is an example yaml configuration file showing all supported items and their default values:
> 
> 
> 	log_level: info
> 
> 	behavior:
> 	  read_only: false
> 	  autocommit: true
> 
> 	user:
> 	  name: root
> 	  password: ""
> 
> 	listener:
> 	  host: localhost
> 	  port: 3306
> 	  max_connections: 1
> 	  read_timeout_millis: 30000
> 	  write_timeout_millis: 30000
> 
> 	databases: []
> 
> 
> SUPPORTED CONFIG FILE FIELDS:
> 
> 	log_level - Level of logging provided. Options are: `trace', `debug`, `info`, `warning`, `error`, and `fatal`.
> 
> 	behavior.read_only - If true database modification is disabled.
> 
> 	behavior.autocommit - If true write queries will automatically alter the working set.  When working with autocommit enabled it is highly recommended that listener.max_connections be set to 1 as concurrency
> 	issues will arise otherwise.
> 
> 	user.name - The username that connections should use for authentication.
> 
> 	user.password - The password that connections should use for authentication.
> 	listener.host - The host address that the server will run on.  This may be `localhost` or an IPv4 or IPv6 address.
> 
> 	listener.port - The port that the server should listen on.
> 
> 	listener.max_connections - The number of simultaneous connections that the server will accept.
> 
> 	listener.read_timeout_millis - The number of milliseconds that the server will wait for a read operation.
> 
> 	listener.write_timeout_millis - The number of milliseconds that the server will wait for a write operation.
> 
> 	databases - a list of dolt data repositories to make available as SQL databases. If databases is missing or empty then the working directory must be a valid dolt data repository which will be made available
> 	as a SQL database
> 
> 	databases[i].path - A path to a dolt data repository.
> 
> 	databases[i].name - The name that the database corresponding to the given path should be referenced via SQL.
> ```
> 
> Try changing the timeouts to 10 minutes or something large: (600000)

thanks ,try it now

**Comment by GodGavin** [comment]
@bheni when i alter the settings,and try again,it is still the  same ,anyting wrong of my settings,plesese view this photo below，
![dlotmysqlclientbug](https://user-images.githubusercontent.com/64452311/80555380-b5082900-8a02-11ea-8bdb-a93f85cfe2df.jpg)

**Comment by cfljam** [comment]
is the yaml file passed as a parameter to dolt sql-server or placed  somewhere or linked via config settings?

**Comment by GodGavin** [comment]
> is the yaml file passed as a parameter to dolt sql-server or placed somewhere or linked via config settings?
@cfljam 
... i did not  find where it is,so i just alert it by dolt config --global --add  listener.read_timeout_millis 600000 ,hahaha,maybe it is not worked like this

**Comment by zachmu** [comment]
You have to pass your yaml file to the sql-server command like so:

`dolt sql-server --config <file>`

Check out the help for the command by running `dolt sql-server --help`

**Comment by zachmu** [comment]
Actually, it looks like the updated help text for that command still need to be updated, so running --help won't work yet. Sorry about that.

https://github.com/liquidata-inc/dolt/pull/636

**Comment by GodGavin** [comment]
thanks a lot， i need to learn more ，hope dolt to be a big  ip project one day！

**Comment by bheni** [comment]
@GodGavin We just pushed a release (0.16.3) that has the new help text and fixed an issue with our release process.  Please try this release.
