### ISSUE TITLE
Import rebuilds indexes

### ISSUE THREAD

**Issue by Hydrocharged** [liquidata-inc/dolt#666]
`dolt table import` rebuilds any indexes that are on the target table. Rather than changing the current code to allow for index writes, it should be rewritten to use the same code path that SQL uses.

Of note, `dolt table cp` shares most of its code with `dolt table import`, and should probably be simplified so that the old code can be completely eliminated.

**Comment by andrew-wm-arthur** [comment]
@Hydrocharged can we close this now?
