### ISSUE TITLE
Installation script quietly fails

### ISSUE THREAD

**Issue by apoorvalal** [liquidata-inc/dolt#672]
Current script at https://github.com/liquidata-inc/dolt/releases/latest/download/install.sh  has no linebreaks and thus is read in as a comment, so fails to install

![image](https://user-images.githubusercontent.com/12086926/81492747-2e97e680-924f-11ea-925f-be4438d4f14c.png)

**Comment by apoorvalal** [comment]
Seems to have been fixed.

**Comment by reltuk** [comment]
Wow, thanks for reporting. We're tracking down the newly introduced regression in our release process. There should be newlines in there.
