### ISSUE TITLE
The apache license is missing the certain copyright owner

### ISSUE THREAD

**Issue by marpme** [liquidata-inc/dolt#726]
https://github.com/liquidata-inc/dolt/blob/87a5c23424867af8ff9bb80560e0caf093e3d484/LICENSE#L190

This should be filled out at best otherwise, the apache license is likely to be "invalid"?

**Comment by marpme** [comment]
Seems like this part is only a boilerplate that can be used as an header for source code. 
As described in here: https://github.com/liquidata-inc/dolt/blob/87a5c23424867af8ff9bb80560e0caf093e3d484/LICENSE#L179-L188

This is likely to be closed then.

**Comment by reltuk** [comment]
Thanks for the report and the follow up. We appreciate it :).
