### ISSUE TITLE
README refers to 'GOROOT' incorrectly

### ISSUE THREAD

**Issue by carlmjohnson** [liquidata-inc/dolt#741]
`GOROOT` is a detail of compiling the Go language as a language developer. (It lets you change files in the standard library.) Normal users never interact with it in any way. `GOPATH` is what the docs mean.

**Comment by reltuk** [comment]
Whoops, you're totally right. Thank's for the report.

PR out here which should fix this: https://github.com/liquidata-inc/dolt/pull/745

**Comment by reltuk** [comment]
Thanks again!
