### ISSUE TITLE
dolt sql -q "delete from table" for a ~100M row table went into swap and would not complete

### ISSUE THREAD

**Issue by timsehn** [liquidata-inc/dolt#78]
Dolt ended up using 56Gb of memory on my 16Gb machine. I killed it after about 45 minutes.

**Comment by reltuk** [comment]
@Hydrocharged Was this fixed in https://github.com/liquidata-inc/dolt/commit/ed3dc4de5f0d847d6d591920644c94c9c56f9476 ?

**Comment by timsehn** [comment]
Yes. Fixed.

**Comment by Hydrocharged** [comment]
I apologize, I haven’t been keeping up with the issues regarding whether I’ve done work relevant to them or not!
