### ISSUE TITLE
Dropping named foreign key does not allow the foreign key name to be reused 

### ISSUE THREAD

**Issue by coffeegoddd** [liquidata-inc/dolt#830]
attempting to reuse a foreign key name results in an error at commit time:
```
ALTER TABLE nibrs_month DROP FOREIGN KEY NIBRS_MONTH_AGENCY_ID_FK;
ALTER TABLE nibrs_month ADD CONSTRAINT NIBRS_MONTH_AGENCY_ID_FK FOREIGN KEY (AGENCY_ID) REFERENCES agencies(AGENCY_ID);
```

```
$ dolt commit -m 'change reference table of foreign key'
error: Failed to commit changes.
cause: foreign key `NIBRS_INCIDENT_AGENCY_ID_FK` requires the referenced table `cde_agencies`
```

**Comment by coffeegoddd** [comment]
For clarity:
I had a foreign key created called `NIBRS_MONTH_AGENCY_ID_FK` that referenced a table `cde_agencies`.
i needed to drop `cde_agencies` and make a table called `agencies` and remap the foreign key,
so I dropped `NIBRS_MONTH_AGENCY_ID_FK` that referenced `cde_agencies`
and added `NIBRS_MONTH_AGENCY_ID_FK` that referenced `agencies

**Comment by zachmu** [comment]
Skipped dolt test?

**Comment by coffeegoddd** [comment]
closing as pulling `master` seems to fix this!
