### ISSUE TITLE
Dolt Sync for Oracle 

### ISSUE THREAD

**Issue by chrisfw** [liquidata-inc/dolt#863]
Hi,
Thanks for creating this project!  I love the concept of Dolt and feel it can really benefit DevOps CI/CD.  I specifically see this as a potential lifesaver with configuration table schema and data evolution as product versions change.  As you mention somewhere, Dolt isn't meant to replace high volume transactional databases, but rather complement them and allow for auditing, insights and transformations that would otherwise require a lot of complex coding and gyrations (we are doing this). Unfortunately, although I wish our application data store were hosted on Postgres, we are stuck with Oracle.  I discovered your Sync project and I am very interested in the implementation for Oracle.  You mention on the Sync project doc that you will be expanding to more relational database implementations including MS SQL Server and Oracle and that you will be supporting schema syncing from Dolt to any of the supported database implementations.
Are you able to share where the Oracle Sync implementation lies on your roadmap?
Regards,
Chris Whelan

**Comment by timsehn** [comment]
Since you asked for it, we'll get it on our roadmap.

Here's the actual code to the postgres one. https://github.com/liquidata-inc/doltpy/blob/master/doltpy/etl/sql_sync/postgres.py. It's Python, pretty minimal and relies on SQL Alchemy. We'd welcome an open source contribution. 

Otherwise, we'll slot it in in the next month or two.

**Comment by chrisfw** [comment]
Hi Tim,

Thanks for your quick response.  I appreciate it.  I would like to tackle
it and will see what I can do, but I am not sure how much time I will have
to dedicate given the requirements of my full time gig.  FYI, before I
discovered your sync work I was looking at SQLLines for this purpose which
although the project seems stalled, may at least provide some solid info
for mapping MySQL data types to Oracle equivalents.  That said, it sounds
like SQL Alchemy may already have the smarts necessary for this, but I am
not sure about that.

Regards,
Chris

**Comment by timsehn** [comment]
No worries. We’ll get it done in the next few weeks and update this issue.

**Comment by chrisfw** [comment]
Awesome,  thanks Tim (and team)!

-Chris

**Comment by chrisfw** [comment]
Hi Tim,

I reviewed the code for the sync and just wanted to confirm that in
the current version secondary indexes aren't being synced?  From the
comments, it also appears that column constraints are not currently
supported due to Dolt not currently supporting that MySQL feature, so there
would need to be a creative workaround to implement that tracking in the
sync as well - is my understanding correct?

Regards,
Chris

**Comment by timsehn** [comment]
Column defaults are shipping in the next Dolt release. We have secondary
indexes implemented but maybe not in sync. If those are requirements, we
can add those features to sync.

--Tim

**Comment by chrisfw** [comment]
That is good to know about column defaults thanks Tim.  If possible,
syncing the indexes along with the column constraints (when they are
available) and foreign key constraints would definitely be welcome and
essential for our use case and indeed I would imagine for the general use
case of maintaining db/data schema evolution in Dolt in sync with a
transactional db.  For example, if a column gets dropped from the schema,
any covering index or dependent foreign key constraint then correspondingly
needs to have the same column removed.  If we aren't tracking/syncing that,
then I believe problems are bound to occur on the transactional db side.

Regards,
Chris

**Comment by timsehn** [comment]
Totally agree. sql-sync is very early so if it is something people want,
we'll need a long project to get it up to snuff. Thanks for the feedback.

**Comment by chrisfw** [comment]
Thanks Tim.  Sounds good.  I’d be happy to assist if you have thoughts on how I could contribute meaningfully.  I can provide additional details on our use cases, etc. and I do have some python experience.

Regards,
Chris

**Comment by oscarbatori** [comment]
@chrisfw closing this issue as we will support this in Doltpy, our Python API. See this [issue]. 

We'd be delighted to hear more about your use-cases, would you be up for joining us on [Discord](https://discord.com/invite/RFwfYpu)? Other folks are there discussing use-cases, and it's the fastest way to get support.
