### ISSUE TITLE
UNIQUE constraint should not enforce on NULL values

### ISSUE THREAD

**Issue by zachmu** [liquidata-inc/dolt#891]
From Balint:

Dolt uses different policy for NULL values in the case of UNIQUE constraints then MySQL.

MySQL enables multiple NULL-s for a column if it has UNIQUE constraint on it, does not consider these violation.

Dolt follows here the solution like I think postgreSQL which only enables one NULL in a UNIQUE constraint field.

We designed or db with the MySQL logic. What is the reason Dolt does not follow this like in MySQL?

**Comment by Hydrocharged** [comment]
Fixed in https://github.com/liquidata-inc/dolt/pull/894
